spring:
  application:
    name: superduper-example-jdbc
  datasource:
    url: jdbc:postgresql://localhost:5432/superduper
    username: superduper
    password: superduper
  sql:
    init:
      mode: always

superduper:
  consumer:
    type: spring
  kafka:
    bootstrap-servers: localhost:9092
    group-id: example-jdbc
    topic: superduper.example

logging:
  level:
    root: INFO